//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogWalk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Walk
    {
        public int ID { get; set; }
        public int WalkStatusID { get; set; }
        public Nullable<int> WalkerID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public System.DateTime DateOfWalk { get; set; }
    
        public virtual Walker Walker { get; set; }
        public virtual WalkStatu WalkStatu { get; set; }
    }
}
